apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice
        image: python:3.12
        command: ["python", "/app/app.py"]
        ports:
        - containerPort: 5000
